.TH "Info" 3 "Fri Jun 3 2022" "Version 1" "librick-and-morty" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Info \- structure for \fBInfo\fP page\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBcount\fP"
.br
.ti -1c
.RI "size_t \fBpages\fP"
.br
.ti -1c
.RI "char * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure for \fBInfo\fP page\&. 

struct \fBInfo\fP have typedef : rm_info_t 

.SH "Author"
.PP 
Generated automatically by Doxygen for librick-and-morty from the source code\&.
