.TH "Mem" 3 "Thu Jan 13 2022" "Version 0.1.0" "Rick And Morty C Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mem
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBptr\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rick And Morty C Library from the source code\&.
