.TH "RM_episode_array" 3 "Fri Jun 3 2022" "Version 1" "librick-and-morty" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RM_episode_array \- Structure for an array of \fBRM_episode\fP struct and its length\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <episode\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrm_episode_t\fP ** \fBda_episode\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for an array of \fBRM_episode\fP struct and its length\&. 
.SH "Field Documentation"
.PP 
.SS "\fBrm_episode_t\fP** da_episode"
An 'Array' of struct \fBRM_episode\fP 
.SS "size_t len"
Len of the 'Array' 

.SH "Author"
.PP 
Generated automatically by Doxygen for librick-and-morty from the source code\&.
