.TH "RM_location_array" 3 "Thu Jan 13 2022" "Version 0.1.0" "Rick And Morty C Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RM_location_array \- Structure for an array of \fBRM_location\fP struct and its length\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <location\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrm_location_t\fP ** \fBda_location\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for an array of \fBRM_location\fP struct and its length\&. 
.SH "Field Documentation"
.PP 
.SS "\fBrm_location_t\fP** da_location"
An 'Array' of struct \fBRM_location\fP 
.SS "size_t len"
Len of the 'Array' 

.SH "Author"
.PP 
Generated automatically by Doxygen for Rick And Morty C Library from the source code\&.
