.TH "RM_character_array" 3 "Thu Jan 13 2022" "Version 0.1.0" "Rick And Morty C Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RM_character_array \- Structure for an array of \fBRM_character\fP struct and its length\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <character\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBRM_character\fP ** \fBda_character\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for an array of \fBRM_character\fP struct and its length\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBRM_character\fP** da_character"
An 'array' of struct \fBRM_character\fP 
.SS "size_t len"
Len of the 'Array' 

.SH "Author"
.PP 
Generated automatically by Doxygen for Rick And Morty C Library from the source code\&.
