.TH "RM_dict" 3 "Thu Jan 13 2022" "Version 0.1.0" "Rick And Morty C Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RM_dict \- Structure for 'name' and 'url' string for 'origin' and 'location' field of \fBRM_character\fP structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <character\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBurl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for 'name' and 'url' string for 'origin' and 'location' field of \fBRM_character\fP structure\&. 
.SH "Field Documentation"
.PP 
.SS "char* name"
Name (string) 
.SS "char* url"
Url (string url) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Rick And Morty C Library from the source code\&.
